# Generated by Django 2.2.1 on 2019-05-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='url',
            field=models.FileField(upload_to=''),
        ),
    ]
