# Generated by Django 2.2.1 on 2019-05-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_auto_20190516_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='url',
            new_name='file',
        ),
    ]
