# Generated by Django 2.2.1 on 2019-05-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_auto_20190516_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='file',
        ),
        migrations.AddField(
            model_name='track',
            name='url',
            field=models.CharField(default='http://example.com', max_length=50),
            preserve_default=False,
        ),
    ]
